from sine.constants import sickass_placeholder_url
from sine.cover import Cover
from sine.link import Link
from sine.loggable import Loggable
from sine.metadata import Metadata
from bs4 import BeautifulSoup
from typing import LiteralString
from requests import get
from datetime import datetime

class Site(Loggable):
    """Very very basic youtube site metadata scrapper"""
    def __init__(self, url:str|LiteralString|Link=sickass_placeholder_url, **kwargs):
        super().__init__(**kwargs)
        self.url = url

    def reload(self):
        self.info("requesting player...")
        self.g = get(str(self.url))


    def obtain_metadata(self, _debug_dump:bool=False):
        """scrapes the target site specified and returns a Metadata item"""
        self.reload()
        if self.g.status_code==200:
            self.info("parsing meta...")
            bs = BeautifulSoup(self.g.content, features="html.parser")
            if _debug_dump:
                with open("./dump.html", "w", encoding="utf-8") as f:
                    f.write(bs.prettify())
            title_meta = bs.find("meta", {"name":"title"})
            if not title_meta:
                self.warn("unable to obtain reference to title, please expect no title meta :(")
            author_submeta = bs.find("span", {"itemprop":"author"})
            artist_meta = None
            channel_link_meta = None
            if author_submeta:
                artist_meta = author_submeta.find("link", {"itemprop":"name"})
                channel_link_meta = author_submeta.find("link", {"itemprop": "url"})
            else:
                self.warn("unable to obtain reference to author, please expect no artist and artist cover meta :(")
            artist_cover_meta = None
            if channel_link_meta:
                self.info("requesting channel...")
                cg = get(channel_link_meta.get("href"))
                if cg.status_code==200:
                    bs_two = BeautifulSoup(cg.content, features="html.parser")
                    artist_cover_meta = bs_two.find("link", {"itemprop": "thumbnailUrl"})
                else:
                    self.warn(f"unable to obtain channel metadata with status code {str(cg.status_code)}. please expect no artist cover :(")
            elif author_submeta:
                self.warn(f"unable to obtain reference to channel, please expect no artist cover :(")
            thumb_meta = bs.find("link", {"itemprop": "thumbnailUrl"})
            time_meta = bs.find("meta", {"itemprop": "datePublished"})
            if not thumb_meta:
                self.warn("unable to obtain reference to thumbnail/cover, please expect no cover meta :(")
            if not time_meta:
                self.warn("unable to obtain reference to creation date, please expect no time meta :(")
            m = Metadata()
            if title_meta:
                m.title = title_meta.get("content")
            if artist_meta:
                if artist_meta.get("content").endswith("- Topic"):
                    self.warn("it appears this channel was auto-generated by YouTube (or another service). metadata may be inaccurate or not work as expected.")
                m.artist = artist_meta.get("content").replace(" - Topic", "")
            m.album = m.artist
            if thumb_meta:
                m.cover = Cover(thumb_meta.get("href"), "image/jpeg", logger=self._logger, name="front")
                m.icon = m.cover.clone(name="thumbnail")
            if artist_cover_meta:
                m.artist_cover = Cover(artist_cover_meta.get("href"), "image/png", logger=self._logger, name="artist")
            if time_meta:
                time_meta_con = datetime.fromisoformat(time_meta.get("content"))
                m.year_created = time_meta_con.year
            m.display(self.info)
            return m
        else:
            self.warn(f"unable to connect to youtube player with status code {str(self.g.status_code)}, no metadata will be provided :(")
